twig:
    default_path: '%kernel.project_dir%/templates'
    paths: 
         '%kernel.project_dir%/src/Bundles/ContabilidadBundle/Resources/templates': Contabilidad
         '%kernel.project_dir%/src/Bundles/CineBundle/Resources/templates': Cine
         '%kernel.project_dir%/src/Bundles/PizzonBundle/Resources/templates': Pizzon

when@test:
    twig:
        strict_variables: true
