twig:
    default_path: '%kernel.project_dir%/templates'
    paths: 
        '%kernel.project_dir%/vendor/apa1112/cinebundle/templates': CineBundle

when@test:
    twig:
        strict_variables: true
