twig:
    default_path: '%kernel.project_dir%/templates'
    paths: 
         '%kernel.project_dir%/src/ContabilidadBundle/Resources/templates': Contabilidad

when@test:
    twig:
        strict_variables: true
