#index:
#    path: /
#    controller: App\Controller\DefaultController::index
contabilidad_route:
  path: /contabilidad
  controller: App\Bundles\ContabilidadBundle\Controller\ContabilidadController::index

contabilidad_section1:
  path: /contabilidad/section1
  controller: App\Bundles\ContabilidadBundle\Controller\ContabilidadController::section1

contabilidad_section2:
  path: /contabilidad/section2
  controller: App\Bundles\ContabilidadBundle\Controller\ContabilidadController::section2

contabilidad_section3:
  path: /contabilidad/section3
  controller: App\Bundles\ContabilidadBundle\Controller\ContabilidadController::section3

cine_route:
  path: /cine
  controller: App\Bundles\CineBundle\Controller\CineController::cineIndex

cine_section1:
  path: /cine/section1
  controller: App\Bundles\CineBundle\Controller\CineController::cineSection1

cine_section2:
  path: /cine/section2
  controller: App\Bundles\CineBundle\Controller\CineController::cineSection2

cine_section3:
  path: /cine/section3
  controller: App\Bundles\CineBundle\Controller\CineController::cineSection3

pizzon_route:
  path: /pizzon
  controller: App\Bundles\PizzonBundle\Controller\PizzonController::pizzonIndex

pizzon_section1:
  path: /pizzon/section1
  controller: App\Bundles\PizzonBundle\Controller\PizzonController::pizzonSection1

pizzon_section2:
  path: /pizzon/section2
  controller: App\Bundles\PizzonBundle\Controller\PizzonController::pizzonSection2

pizzon_section3:
  path: /pizzon/section3
  controller: App\Bundles\PizzonBundle\Controller\PizzonController::pizzonSection3